version: 0.2

phases:
  install:
    commands:
      - bundle install
  build:
    commands:
      - sudo chown -R $(whoami) /codebuild/output/*
      - bundle exec jekyll build
      - aws s3 sync --delete _site/ s3://ahmedbhamaws.net